In [1]:
from astropy.io import fits
import numpy as np
from astropy.table import Table
import pandas as pd
import glob
from astropy.table import vstack
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.backends.backend_pdf import PdfPages
import os

In [2]:
df = pd.read_csv("../Class_wise_v4/Halpha_emitter_wise_noise.csv")
len(df)

1750

In [3]:
# Colors
df['W1_W2'] = df['W1mag'] - df['W2mag']
df['J_H'] = df['Jmag'] - df['Hmag']
df['H_W2'] = df['Hmag'] - df['W2mag']
df['Ks_W3'] = df['Kmag'] - df['W3mag']
df['W1_W4'] = df['W1mag'] - df['W4mag']
df['r_i'] = df['rImag'] - df['imag']
df['r_Ha'] = df['rImag'] - df['Hamag']

Akras et al. (2019):

Three different classification tree models were found that identify
PNe in the best possible way: W1 − W4 ≥ 7.87 and J − H < 1.10
(M1); H − W2 ≥ 2.24 and J − H < 0.50 (M2); and Ks − W3 ≥
6.42 and J − H < 1.31 (M3).

In [4]:
# Modelo M1 (W1-W4 y J-H)
mask_m1 = ((df['W1_W4'] >= 7.87) & (df['J_H'] < 1.10))
    
# Modelo M2 (H-W2 y J-H) - ¡Tu preferido!
mask_m2 = ((df['H_W2'] >= 2.24) & (df['J_H'] < 0.50))
    
# Modelo M3 (Ks-W3 y J-H)
mask_m3 = ((df['Ks_W3'] >= 6.42) & (df['J_H'] < 1.31))

In [5]:
# DataFrames separados
df_m1 = df[mask_m1].copy()
df_m1['model'] = 'M1'
    
df_m2 = df[mask_m2].copy()
df_m2['model'] = 'M2'
    
df_m3 = df[mask_m3].copy()
df_m3['model'] = 'M3'

In [6]:
df_full_PN = pd.concat([df_m1, df_m2, df_m3])
df_full_PN

,Name,RAJ2000,DEJ2000,GLON,GLAT,SourceID,ePos,Class,pStar,pGalaxy,...,PC5,Label,W1_W2,J_H,H_W2,Ks_W3,W1_W4,r_i,r_Ha,model
317,J211937.22+545328.8,319.905078,54.891340,95.544481,3.707010,477336-1-8163,0.034,99.0,0.05,0.95,...,6.159535,-1,2.058,0.707,5.851,9.167,8.593,0.76,1.22,M1
326,J213646.48+562716.6,324.193667,56.454608,98.377140,3.165845,478602-1-4135,0.036,-1.0,1.00,0.00,...,5.922983,-1,2.283,0.319,4.175,8.573,8.838,0.60,1.07,M1
521,J064724.25-000137.8,101.851057,-0.027175,212.496251,-0.909865,650202-4-3360,0.032,-1.0,1.00,0.00,...,5.908355,-1,1.097,0.487,2.281,6.596,8.286,0.49,0.57,M1
566,J063122.56+045019.5,97.844016,4.838763,206.335101,-2.238908,374770-1-743,0.035,99.0,1.00,0.00,...,5.494996,-1,0.299,0.840,1.071,5.188,9.165,1.05,0.77,M1
577,J063149.26+045700.9,97.955238,4.950254,206.287253,-2.089161,429747-2-2779,0.053,-1.0,1.00,0.00,...,5.951644,-1,0.543,0.853,1.906,4.889,8.324,0.86,0.65,M1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1576,J221952.97+561449.7,334.970710,56.247137,102.979530,-0.637602,462337-3-6954,0.034,99.0,0.95,0.05,...,5.658783,-1,0.600,0.245,2.324,6.819,7.446,0.53,0.49,M3
1599,J232247.53+595217.2,350.698023,59.871442,112.015505,-1.108140,476438-4-4802,0.030,-1.0,1.00,0.00,...,5.960554,-1,0.480,0.716,2.586,6.636,8.406,0.56,0.46,M3
1645,J231541.23+620654.4,348.921805,62.115113,111.990056,1.294818,635580-2-2824,0.030,-1.0,1.00,0.00,...,6.214386,-1,0.870,1.184,3.824,6.599,6.397,0.39,0.49,M3
1712,J194557.22+243745.6,296.488437,24.629325,60.873379,-0.034522,364585-1-4405,0.028,-1.0,1.00,0.00,...,6.215732,-1,1.459,0.943,3.984,6.967,7.600,0.64,0.77,M3
1745,J195837.16+312322.7,299.654844,31.389637,68.110241,1.029840,406893-4-17554,0.036,-1.0,1.00,0.00,...,6.112406,-1,1.590,0.650,3.649,7.322,8.054,0.79,0.71,M3

In [7]:
# Ejemplo: Conservar la última aparición
df_full_PN_unique = df_full_PN.drop_duplicates(subset=['Name'], keep='last')

In [10]:
df_full_PN_unique[["RAJ2000", "DEJ2000", "rImag"]]

         RAJ2000    DEJ2000  rImag
566    97.844016   4.838763  17.54
577    97.955238   4.950254  16.29
581    97.916177   4.944209  18.13
583    97.923491   5.026523  19.06
721    99.121919  10.833720  16.51
989   288.178775   5.762863  17.65
1037   82.035785  34.427328  16.22
1225    3.851996  61.238380  16.33
1344   42.693960  60.437394  17.58
1428   34.285149  63.269821  17.84
1570  334.364412  55.817561  16.25
163   305.397248  42.444182  18.50
766    96.318788  19.839286  15.81
1096   80.903620  41.433292  17.35
1174   75.048258  47.861349  16.02
1258   49.006751  51.879498  18.39
24    304.125079  35.945435  15.12
167   306.194127  42.361697  18.05
317   319.905078  54.891340  18.24
326   324.193667  56.454608  16.57
333   326.408336  57.536356  19.25
398   332.132565  57.932962  17.25
521   101.851057  -0.027175  17.54
523   102.184247   0.655899  17.99
527    99.868687   0.830009  16.55
578    97.995416   4.969766  18.20
598   101.164906   6.110649  16.80
738    93.026003  15.154584  16.26
788    94.519785  19.873019  16.75
875    91.177114  30.134169  16.17
930    83.702847  32.853473  16.09
960    85.197307  35.990712  14.92
1077   79.998827  39.026472  17.08
1097   80.915545  42.418316  17.20
1129   77.683946  47.168041  19.14
1224    3.547740  61.003606  18.41
1242    0.715359  63.487220  16.96
1250    1.877464  65.664646  14.86
1342   41.608510  60.104943  17.64
1355   40.478213  60.720893  15.87
1364   45.015158  62.410154  18.35
1378   55.840147  60.710066  17.08
1446   12.820730  64.627858  18.77
1499  302.363366  27.329859  14.97
1576  334.970710  56.247137  14.23
1599  350.698023  59.871442  18.44
1645  348.921805  62.115113  16.82
1712  296.488437  24.629325  17.56
1745  299.654844  31.389637  17.94

In [9]:
# 9. Guardar para crossmatch con LAMOST
df_full_PN.to_csv('../Class_wise_v4/PNe_candidates_noise_Akras.csv', index=False)